# Generated by Django 2.0 on 2017-12-28 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0012_auto_20171228_1652'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('user_from_read', models.BooleanField(default=False)),
                ('user_to_read', models.BooleanField(default=False)),
                ('store_read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='MessageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1_read', models.BooleanField(default=False)),
                ('store_read', models.BooleanField(default=False)),
                ('user_2_read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_list_to_store', to='store.Store')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_list_from', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_list_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created', 'user_1_read', 'user_2_read'),
            },
        ),
        migrations.AddField(
            model_name='message',
            name='message_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_list', to='message.MessageList'),
        ),
        migrations.AddField(
            model_name='message',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_to', to='store.Store'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
