# Generated by Django 2.0 on 2018-01-02 14:40

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
