# Generated by Django 2.0 on 2018-01-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20171228_1652'),
        ('account', '0006_auto_20180102_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='store.Category'),
        ),
    ]
