# Generated by Django 2.0 on 2017-12-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20171227_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='processing_time',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='product',
            name='processing_time',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
