# Generated by Django 2.0 on 2017-12-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20171227_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
