# Generated by Django 2.0 on 2018-01-02 20:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20171228_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
