# Generated by Django 2.0 on 2017-12-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagelist',
            options={'ordering': ('-created', 'user_from_read', 'user_to_read')},
        ),
        migrations.RenameField(
            model_name='messagelist',
            old_name='user_1',
            new_name='user_from',
        ),
        migrations.RenameField(
            model_name='messagelist',
            old_name='user_1_read',
            new_name='user_from_read',
        ),
        migrations.RenameField(
            model_name='messagelist',
            old_name='user_2',
            new_name='user_to',
        ),
        migrations.RenameField(
            model_name='messagelist',
            old_name='user_2_read',
            new_name='user_to_read',
        ),
    ]
