# Generated by Django 2.0 on 2018-01-02 14:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('account', '0003_auto_20171228_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
